#!/usr/bin/env php
<?php
// define('_ENV_', '');
set_time_limit(0);

require 'paths.php';

/* INIT */
require(_CORE_DIR_.'core.php');

/* RUN */
$router = new Asgard\Core\Cli\Router;
$router->run('Asgard\Core\Cli\FrontController', 'main');